### PR TITLE
Multiple bug fixes

### PR DESCRIPTION
**Pull request by parakeet-live**
the commits should be obvious, lmk if i should change anything.

### CODE REVIEW

**Comment by grayhax** [comment]
aren't sign ups broken as well?

**Comment by parakeet-live** [comment]
grayhax said: "Aren't signups broken?"
no they aren't you just have a skill issue

**Comment by SRGNation** [comment]
This is good but the code for checking account deletion instead of using “SELECT * FROM users”
`$stmt = $db->prepare("SELECT * FROM users WHERE id = ?");
    $stmt->bind_param("i", $_SESSION["id"]);
    $stmt->execute();
    $res = $stmt->get_result();
    if($res->num_rows == 0){ `
You can instead do something like this 
`$stmt = $db->prepare("SELECT COUNT(*) FROM users WHERE id = ?");
    $stmt->bind_param("i", $_SESSION["id"]);
    $stmt->execute();
    $res = $stmt->get_result();
    $crow = $res->fetch_assoc();
    if($crow[‘COUNT(*)’] == 0){ ` that way it wouldn’t have to select all the columns in the “users” table each time lol (The code might not work as is because I typed it on a mobile device but you still probably get it)

**Comment by parakeet-live** [comment]
I'll fix it right now

**Comment by parakeet-live** [comment]
Should be good now

**Pull request merged**
